name: redux_optimistic_thunk
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Jason Aguilon <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  redux: ^2.1.1

dev_dependencies:
  test: ^0.12.0
